### ISSUE TITLE
Fix `recipe_url`

### ISSUE THREAD

**Issue by JHertz5** [JHertz5/shopping_list#22]
The `-r|--recipe` URL option is currently broken. Fix it.
```
$ ./bin/shopping_list -r
data connected
input data retrieved
recipes on input list:
        0 - Veggie Bibimbap
        1 - Pan Fried Halloumi
        2 - Pan Fried Halloumi
        3 - Turmeric Chicken
        4 - Lasagna
pick recipe: 0
        Veggie Bibimbap selected
Traceback (most recent call last):
  File "/home/jhertzog/code/shopping_list/./bin/shopping_list", line 15, in <module>
    main()
  File "/home/jhertzog/code/shopping_list/bin/../shopping_list/__main__.py", line 37, in main
    get_recipe_urls.get_recipe_urls()
  File "/home/jhertzog/code/shopping_list/bin/../shopping_list/get_recipe_urls.py", line 67, in get_recipe_urls
    recipe_url_dict = get_all_recipe_urls(recipes_sheet)
  File "/home/jhertzog/code/shopping_list/bin/../shopping_list/get_recipe_urls.py", line 17, in get_all_recipe_urls
    recipe_url   = match_result.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by JHertz5** [comment]
Deleted get_recipe_url in #88 because it was unused. Closing
